### PR TITLE
feat: Added token refresh method to client

### PR DESCRIPTION
**Pull request by frgfm**
This PR introduces the following modifications:
- added token refresh method to API client
- added unittest

Any feedback is welcome!

### CODE REVIEW

**Review by fe51 — COMMENTED** [review]
Hi There, thanks for the PR !

Looks okay to me. 
However, just a question (sorry I might have not been following recent update), but what is the aim of this update ? Does it solve an issue from any other team ?

**Comment by frgfm** [comment]
> Hi There, thanks for the PR !
> 
> Looks okay to me.
> However, just a question (sorry I might have not been following recent update), but what is the aim of this update ? Does it solve an issue from any other team ?

Hi @fe51,

Yes, it allows instantiated client to refresh their token that expire. For the platform this happens since user do not have unlimited tokens :)

**Comment by fe51** [comment]
Okay perfect then :)

Thanks a lot

**Review by fe51 — APPROVED** [review]

**Review by Akilditu — APPROVED** [review]
Thanks for this PR that will ensure the platform longtime run !

**Pull request merged**
