### PR TITLE
feat(main): add a new endpoint for status

### PR DESCRIPTION
**Pull request by RonanMorgan**
An endpoint can be useful for further automation (and I need in order to launch the dev env automatically)

### CODE REVIEW

**Comment by RonanMorgan** [comment]
done

**Comment by RonanMorgan** [comment]
well I removed the prefix="/status" to avoid this behavior ("/status/status") but ok I can refactor to put the code in main.py

**Comment by RonanMorgan** [comment]
done

**Review by frgfm — APPROVED** [review]
Thanks!

**Pull request merged**
