### PR TITLE
refactor: Moved azimuth angle from (-180, +180) to (0, 360)

### PR DESCRIPTION
**Pull request by frgfm**
The azimuth was wrongly constrained between -180 and +180, while it should have been 0 and 360.
This PR fixes that, pinned the `httpx` version which caused problems during testing, and I fixed the client unittests which were failing on a very rare edge case

### CODE REVIEW

**Review by fe51 — DISMISSED** [review]
Thank FG ! Okay to me

**Review by Akilditu — APPROVED** [review]
Thanks for the PR ! 

Seems that some tests failed but the improvement looks good to me !

**Review by mateoIdemia — APPROVED** [review]

**Comment by MateoLostanlen** [comment]
oups wrong account :)

**Review by MateoLostanlen — APPROVED** [review]
Thanks for this little change that will simplify our lives :)

**Pull request merged**
